#!/usr/bin/env bash

# Check if one argument is passed
if [[ "$#" == "1" ]]; then
  # Start process
  if [[ "$1" == "start" ]]; then
    if test -f "/var/run/my_process.pid"; then
      echo "manage_my_process is already running."
    else
      ./manage_my_process & # Start the process in the background
      echo "$!" > /var/run/my_process.pid # Save PID
      echo "manage_my_process started"
    fi

  # Stop process
  elif [[ "$1" == "stop" ]]; then
    if test -f "/var/run/my_process.pid"; then
      PID=$(cat /var/run/my_process.pid)
      if kill "$PID"; then # Attempt to stop the process gracefully
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
      else
        echo "Failed to stop manage_my_process."
      fi
    else
      echo "No process found to stop."
    fi

  # Restart process
  elif [[ "$1" == "restart" ]]; then
    # Stop process if running
    if test -f "/var/run/my_process.pid"; then
      PID=$(cat /var/run/my_process.pid)
      if kill "$PID"; then
        echo "manage_my_process stopped for restart"
      else
        echo "Failed to stop manage_my_process. Forcing stop..."
        kill -9 "$PID" # Force stop if normal kill fails
      fi
      rm /var/run/my_process.pid
    fi

    # Start process
    ./manage_my_process & # Restart the process
    echo "$!" > /var/run/my_process.pid # Save new PID
    echo "manage_my_process restarted"

  else
    echo "Usage: manage_my_process {start|stop|restart}"
  fi

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
