#!/usr/bin/env bash

# manage_my_process script that writes "I am alive!" to /tmp/my_process every 2 seconds

# Infinite loop to write "I am alive!" every 2 seconds
while true; do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
